version: '3'
services:
  xbrain:
    volumes:
      - ./xbrain/Demo/:/home/jovyan/work/
    build:
      ./xbrain/Demo
    ports:
      - "8888:8888"
  dvid:
    image:
      "flyem/dvid"
    volumes:
      - /Users/rodrilm2/Documents/APL/GeorgiaTech/Data/proj4:/dataLoad/
    hostname:
      localhost
    ports:
      - "8000:8000"
  # main:
  #   hostname:
  #     main
  #   build:
  #     ./xbrain_dvid_main
